version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: kartaca
      MYSQL_DATABASE: kartaca
      MYSQL_USER: kartaca
      MYSQL_PASSWORD: kartaca
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"

  airflow:
    image: puckel/docker-airflow:1.10.9
    restart: always
    depends_on:
      - mysql
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW_CORE_SQL_ALCHEMY_CONN=mysql://kartaca:kartaca@mysql/kartaca
      - AIRFLOW_CORE_LOAD_EXAMPLES=False
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./logs:/usr/local/airflow/logs
      - ./plugins:/usr/local/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver

  airflow_scheduler:
    image: puckel/docker-airflow:1.10.9
    restart: always
    depends_on:
      - airflow
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./logs:/usr/local/airflow/logs
      - ./plugins:/usr/local/airflow/plugins
    command: scheduler
